# Generated by Django 5.1.1 on 2024-12-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Web_Ingles', 'new_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='topic',
        ),
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('basic', 'Básico'), ('elementary', 'Elemental')], default='basic', max_length=20),
            preserve_default=False,
        ),
    ]
