# Generated by Django 5.1.1 on 2024-12-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Web_Ingles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('basic', 'Básico'), ('elementary', 'Elemental')], max_length=20),
        ),
    ]
