# Generated by Django 5.1.1 on 2024-12-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Web_Ingles', '0002_alter_quiz_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='sections',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('basico', 'Básico'), ('elemental', 'Elemental')], max_length=20),
        ),
    ]
