# Generated by Django 5.1.1 on 2024-11-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_section_studentprofile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
