# Generated by Django 5.1.1 on 2024-12-09 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_section_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['code'], 'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Perfil de Estudiante', 'verbose_name_plural': 'Perfiles de Estudiantes'},
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El formato debe ser "INU1234-123X" o "INI1234-123X" donde 1234 y 123 son números y X es una letra', regex='^IN[UI]\\d{4}\\s*-\\s*\\d{3}[A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.section'),
        ),
    ]
