# Generated by Django 5.1.1 on 2024-11-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_section_code_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
