# Generated by Django 5.1.1 on 2024-11-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Web_Ingles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allowed_attempts',
            field=models.IntegerField(default=3, help_text='número de intentos permitidos'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'fácil'), ('medium', 'media'), ('hard', 'difícil')], max_length=6),
        ),
    ]
